#
#	makefile for jwarn
# 
CFLAGS = -O3 -c

.c.o:
	gcc $(CFLAGS) -o$@ $<

OBJ    =  JWARN.o TABLE.o RULES.o

jwarn:	$(OBJ)
		gcc -o$@ $(OBJ)

clean:
	rm *.o jwarn

jwarn.o: JWARN.c TABLE.h
table.o: TABLE.c TABLE.h
rules.o: RULES.c TABLE.h MESSAGE.h
